"""Introspect the FastAPI sidecar and emit docs/API_SURFACE.md (Phase G)."""

from __future__ import annotations

from pathlib import Path

from app.db import connect
from app.service.app import create_app

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "API_SURFACE.md"


def _auth_for_route(path: str) -> str:
    return "none" if path == "/health" else "bearer"


def main() -> None:
    db_path = ":memory:"
    app = create_app(token="__dump__", conn_factory=lambda: connect(db_path))
    rows: list[dict[str, str]] = []
    for route in sorted(app.routes, key=lambda r: getattr(r, "path", "")):
        path = getattr(route, "path", None)
        methods = sorted(getattr(route, "methods", []) or [])
        if not path or not methods:
            continue
        response_model = getattr(route, "response_model", None)
        model_name = getattr(response_model, "__name__", "") if response_model else ""
        for method in methods:
            if method == "HEAD":
                continue
            rows.append(
                {
                    "method": method,
                    "path": path,
                    "auth": _auth_for_route(path),
                    "response_model": model_name or "—",
                    "module": "app.service.routes.registry",
                }
            )

    lines = [
        "# API surface — FastAPI sidecar",
        "",
        "Generated by `uv run python scripts/dump_api_surface.py`. Do not hand-edit.",
        "",
        "| Method | Path | Auth | Response model | Module |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| {row['method']} | `{row['path']}` | {row['auth']} | {row['response_model']} | {row['module']} |"
        )
    lines.append("")
    lines.append(f"Total routes: **{len(rows)}**")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
